name: memorime_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  google_sign_in: ^6.3.0
  firebase_database: ^11.3.5
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  flutter_quill: ^11.4.1
  image_picker: ^1.0.7
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_quill_extensions: ^11.0.0
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.5.1
  firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

